Verstegen/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Verstegen.Models;
using X.PagedList;

namespace Verstegen.Controllers
{
    public class SearchController : Controller
    {
        private readonly MyContext db;

        List<Object> resultList;

        int Amount;

        public SearchController(MyContext myContext)
        {
            db = myContext;
            resultList = new List<object>();
            Amount = 6;
        }

        public IActionResult Index(string result, int page)
        {
            if(page < 1)
            {
                page = 1;
            }

            ViewBag.Search = result;

            //Haalt alle object op van de Model Blog
            var blogList = db.Blogs.Where(b => b.Title.Contains(result) || b.Subject.Contains(result) || b.SubTitle.Contains(result) || b.Text.Contains(result) || b.Quote.Contains(result) || b.QuoteFrom.Contains(result) || b.SubText.Contains(result) || b.Date.ToString().Contains(result) || b.Type.Contains(result)).ToList();
            //Haalt alle object op van de Model Recipe
            var recipeList = db.Recipes.Where(r => r.Title.Contains(result) || r.SubTitle.Contains(result) || r.Type.Contains(result) || r.AmountOfPeople.Contains(result) || r.Procedure.Contains(result) || r.Decoration.Contains(result) || r.Ingredients.Any(a => a.Name.Contains(result) || a.Gram.ToString().Contains(result) || a.ArticleNumber.ToString().Contains(result) || a.Percentage.ToString().Contains(result))).ToList();
            //Haalt alle object op van de Model Product
            var productList = db.Products.Where(p => p.Title.Contains(result) || p.Type.Contains(result) || p.Description.Contains(result) || p.Contents.Contains(result) || p.AltString.Contains(result) || p.ProductDetails.Contains(result)).ToList();

            //Voegt de List met blogs toe aan de Object List
            resultList = (from x in blogList select (Object)x).ToList();
            //Voegt de List met Recipes toe aan de Object List
            resultList.AddRange((from x in recipeList select (Object)x).ToList());
            //Voegt de List met Products toe aan de Object List
            resultList.AddRange((from x in productList select (Object)x).ToList());

            ViewBag.TestList = resultList;

            //Geeft alleen de benodigde Objecten mee aan de view en houd rekening mee met de pagina.
            //De Functie ToPagedList() is een externe Package die de pagenavigation makkelijk maakt.
            ViewBag.resultList = resultList.ToPagedList(page, Amount);
            ViewBag.AmountPages = (int)Math.Ceiling((Double)resultList.Count() / Amount);
            ViewBag.Page = page;
            ViewBag.Result = result;

            return View();
        }
    }
}

Verstegen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Verstegen</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" type="text/css" media="screen" runat="server" />
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
</head>
<body>
    <div class="header-position-style">
        <div class="logo-container">
            <a href="/Home"><img class="logo-img" src="~/images/footer/logo-verstegen.svg" alt="Verstegen Logo" /></a>
        </div>

        <!-- Navigation -->
        <div class="menu-toggle-wrapper rounded">
            <div class="row">
                <span class="food-industry">Food industry</span>
                <a class="menu-toggle rounded" href="#">
                    <span class="fa fa-bars"></span>
                </a>
                <div class="changeLang ">
                    <input type="radio" name="l" id="toNl" checked />
                    <label for="toNl"></label>
                    <input type="radio" name="l" id="toEn" />
                    <label for="toEn"></label>
                    <a href="#" id="search-icon" onclick="displaySearch()">
                        <span class="fas fa-search"></span>
                    </a>
                    <div style="display: none;" class="mb-3 mr-5" id="search-input">
                        <form action="@Url.Action("Index", "Search")" method="GET">
                            <input id="result" name="result" type="text" class="form-control w-100 search-input" placeholder="Search ..." autocomplete="off">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav mt-5">
                <li class="sidebar-nav-item mt-5">
                    <a class="js-scroll-trigger" href="/home">Home</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/howwework">How we work</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="@Url.Action("Index", "Inspiration", new { page = 1, id = 0 })">Inspiration</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/newsandevents">News & events</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/products">Products</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/recipes">Recipes</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/contact">Contact</a>
                </li>
                <li class="sidebar-nav-item">
                    <a class="js-scroll-trigger" href="/about">About Verstegen</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="body-content">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container-fluid main-color">
            <div class="container">
                <div class="row pt-5 justify-content-center">
                    <h3>Our certificates</h3>
                </div>
                <div class="row py-2 justify-content-center">
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                    <div class="category"><a href="~/files/Certificate.pdf" download><img src="~/images/footer/icon.png" /></a></div>
                </div>
                <div class="row pb-5 justify-content-center">
                    <h5>Click on a certificate to download</h5>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row py-5 px-5 secondary-color">
                <div class="col-sm-1"></div>
                <div class="col-sm-3">
                    <div>
                        <h4 class="footer-sub-title">Verstegen Spices & Sauces</h4>
                        <h5>t.a.v. Business Unit Food Industry</h5>
                        <h5>Industrieweg 161</h5>
                        <h5>3044 AS Rotterdam</h5>
                        <h5>The Netherlands</h5>
                    </div>
                </div>
                <div class="col-sm-3">
                    <h4 class="footer-sub-title">Contact details</h4>
                    <h5>+31 (0)10-2455160</h5>
                    <a href="mailto:foodindustry@verstegen.eu?"><h5>foodindustry@verstegen.eu</h5></a>
                    <h5>Send us a message</h5>
                </div>
                <div class="col-sm-3">
                    <h4 class="footer-sub-title">Newsletter</h4>
                    <h5 id="newsletter-text">Stay up to date about Verstegen</h5>
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="search" placeholder="E-mail address" aria-label="Search">
                        <button class="btn red-color my-2 my-sm-0" type="submit">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row py-4 px-4">
                <div class="col-sm-1">
                    <a href="/Home"><img src="~/images/footer/logo-verstegen.svg" /></a>
                </div>
                <div class="col-sm-3 footer-copyright">
                    <p>&#9400;2017 Verstegen Sauces & Spices</p>
                </div>
                <div class="col-sm-4">
                    <img src="~/images/footer/enjoygreattaste.png" />
                </div>
                <div class="col-sm-4 d-flex justify-content-center">
                    <a href="https://www.youtube.com/channel/UCm3nQjm1SwJ2S_HsCs3E_8w">
                        <div class="square">
                            <img src="~/images/footer/youtube-logo.svg" alt="YouTube" />
                        </div>
                    </a>
                    <a href="https://www.facebook.com/VerstegenNL">
                        <div class="square">
                            <img src="~/images/footer/facebook-logo.svg" alt="Facebook" />
                        </div>
                    </a>
                    <a href="https://twitter.com/verstegen_nl">
                        <div class="square">
                            <img src="~/images/footer/twitter-logo.svg" alt="Twitter" />
                        </div>
                    </a>
                </div>
            </div>

        </div>
    </footer>

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/js/anchor.js"></script>
    <script src="/js/site.js?v=6YWg9zDRz2a6ix9LIONgRvXZXbOGqA9NaplyUOKTg5M"></script>
    <script src="~/js/carousel.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>